#!/usr/bin/env bash
#
# XBar menu plugin for lima
#
# Copyright 2021, Joe Block <jpb@unixorn.net>
#
# <xbar.title>Lima Control</xbar.title>
# <xbar.version>v1.0</xbar.version>
# <xbar.author>Joe Block</xbar.author>
# <xbar.author.github>unixorn</xbar.author.github>
# <xbar.desc>Control Lima VM</xbar.desc>
# <xbar.dependencies>Lima</xbar.dependencies>
# <xbar.image>http://i.imgur.com/nQ6LzvZ.png</xbar.image>
#
# Dependencies: 
#   lima - https://github.com/lima-vm/lima

set -o pipefail
if [[ -n "$DEBUG" ]]; then
  set -x
fi

function cleanup() {
  if [[ -d "$SCRATCH_D" ]]; then
    rm -fr "$SCRATCH_D"
  fi
}

function debug() {
  if [[ -n "$DEBUG" ]]; then
    echo "$@"
  fi
}

function fail() {
  printf '%s\n' "$1" >&2  ## Send message to stderr. Exclude >&2 if you don't want it that way.
  exit "${2-1}"  ## Return a code specified by $2 or 1 by default.
}

function has() {
  # Check if a command is in $PATH
  which "$@" > /dev/null 2>&1
}

# Set up a working scratch directory
SCRATCH_D=$(mktemp -d)

if [[ ! "$SCRATCH_D" || ! -d "$SCRATCH_D" ]]; then
  echo "Could not create temp dir"
  exit 1
fi

trap cleanup EXIT

export PATH="$PATH:/usr/local/bin"

status=$(limactl status | grep default)

# Output
echo "lima status $status"
echo "---"
echo "In: $in | color=$IN_SERVICE_COLOR"
echo "Out: $out | color=$OUT_SERVICE_COLOR"